### PR TITLE
Add epehemerals

### PR DESCRIPTION
**Pull request by DRSchlaubi**
This uses ephemeral for this command: (discussion is welcome)

Clarification for tags: info, delete, raw

# Credits
CommandKiller: @Amejonah1200

### CODE REVIEW

**Comment by Amejonah1200** [comment]
I disagree to make rank commands ephemeral. How do I flex with my levels then? :(

**Comment by NyCodeGHG** [comment]
@Amejonah1200 just take a screenshot of the output and send that into the channel and flex with that.

**Comment by Amejonah1200** [comment]
Well, I can just edit it with Ctrl+Shift+I

**Comment by DRSchlaubi** [comment]
...

**Comment by daspositioned** [comment]
Rank, Tag and Blacklist command should not be ephemeral

**Comment by DRSchlaubi** [comment]
> Rank, Tag and Blacklist command should not be ephemeral

Why would the most annoying command which's entire purpose it is to show user-specific information be public

**Comment by daspositioned** [comment]
> Why would the most annoying command which's entire purpose it is to show user-specific information be public

For moderation purposes. Additionally, blacklist and some tag commands are relevant for all users

**Comment by DRSchlaubi** [comment]
> > Why would the most annoying command which's entire purpose it is to show user-specific information be public
> 
> For moderation purposes. Additionally, blacklist and some tag commands are relevant for all users

I don't see how levels would be required for mod purposes, especially if you consider that a user can delete any command response using command responses just sounds like a lazy excuse not to make a proper log

**Comment by daspositioned** [comment]
> 
> 
> > > Why would the most annoying command which's entire purpose it is to show user-specific information be public
> > 
> > 
> > For moderation purposes. Additionally, blacklist and some tag commands are relevant for all users
> 
> I don't see how levels would be required for mod purposes, especially if you consider that a user can delete any command response using command responses just sounds like a lazy excuse not to make a proper log

I'll work on a log but until then we can't use ephemerals. 
Level messages are sometimes needed, for instance when restoring the data of a user. I agree, it's not that important but IMO it should be a normal message too (for now?).

**Comment by DRSchlaubi** [comment]
the entire reason why epehmerals was being worked on is to make ranks ephemeral. There should be backups of the database using the output of /rank of a backup is just unprofessional

**Comment by DRSchlaubi** [comment]
Will be superseeded soon

**Pull request closed without merging**
