### PR TITLE
Feature/autohelp improvements

### LINKED ISSUE #70: Require argument in google command
https://rice.by.devs-from.asia/DiscordPTB_oT6fkmtims.png LOOKS UGLY @JohnnyJayJay

### PR DESCRIPTION
**Pull request by jkoenig134**
closes #70

### CODE REVIEW

**Comment by DRSchlaubi** [comment]
Yes we do

**Comment by jkoenig134** [comment]
@DRSchlaubi OCR was completely removed from this PR/Branch. And reactions on a PR-comment are the wrong place to decide about such a feature.

**Comment by DRSchlaubi** [comment]
Booooo!

**Comment by DRSchlaubi** [comment]
OCR is still the best and coolest feature for auto-help, just renaming the PR and deleting my comments won't change that

**Comment by jkoenig134** [comment]
OCR was removed 5 days ago. The PR doesn´t have to do sth with it.
https://github.com/devcordde/DevcordBot/pull/48/commits/8f7c68690fc9a76069556c62b12c8af0836df1d1

**Comment by DRSchlaubi** [comment]
https://rice.by.devs-from.asia/chrome_qRD4EKGJao.png

**Review by daspositioned — APPROVED** [review]

**Pull request merged**
