### PR TITLE
fix: correct max length of normal messages

### LINKED ISSUE #197: IllegalArgumentException: Value too big for database
Sentry Issue: [DEVCORDBOT-J](https://sentry.io/organizations/devcordde/issues/2394879980/?referrer=github_integration)

```
IllegalArgumentException: Value '> Was bedeuted der java.lang.UnsupportedClassVersionError?

Wenn du einen `java.lang.UnsupportedClassVersionError` während des Ladens deines Plugins bekommst bedeutet dies, dass du zum kompilieren deines Plugins eine neuere Java Version als zum laden (Starten des Minecraft servers) verwendet hast.

Sollte die Version, die dir deine IDE anzeigt, neuer sein kannst du folgendes tun:

**Möglichkeit 1:**  Du kompilierst mit der Version (oder älter als) die zum ausführen brauchst (siehe `Hinweis 3`, kann auch andere Version angegeben werden).

**Möglichkeit 2:** Du lädst dir das JDK Version passend zu deiner zu kompilierenden JRE version herunter (siehe `/t java-installation`).

**Beispiel:** Java 8 PC, Java 16 IDE:
 - Hinweis 3
 - oder Java 16 downloaden und installieren.

Hinweis 1: Mit `/t major-versions` kannst du herausfinden was die major Version (die Zahlen 52, 55 und andere) bedeutet.
Hinweis 2: Du kannst auch das JRE innerhalb deines JDKs bennutzen um den Server zu starten. (BiVieh Fanboiiis hier klicken: ||Dieses findet ihr ggf. auf eurem Desktop im Development Ordner||). Dieses findet ihr im `bin/` Verzeichnisse eures JDKs (`java(.exe)`).
__Hinweis 3: Benutze `/t compile-java-8` um herauszufinden wie du deine Version zum kompilieren (auf Java 8) änderst.__' can't be stored to database column because exceeds length (1048)
    at org.jetbrains.exposed.sql.VarCharColumnType.notNullValueToDB(ColumnType.kt:544)
    at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.valueToDB(ColumnType.kt:37)
    at org.jetbrains.exposed.sql.ColumnType.valueToDB(ColumnType.kt:74)
    at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters(PreparedStatementApi.kt:13)
    at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters(JdbcPreparedStatementImpl.kt:12)
...
(30 additional frame(s) were not displayed)

An error occurred whilst command execution
```

### PR DESCRIPTION
**Pull request by daspositioned**

### CODE REVIEW

**Review by DRSchlaubi — CHANGES_REQUESTED** [review]
That constant is supposed to match the length of a message the constant above it is for longer texts

**Comment by daspositioned** [comment]
The constant I changed is for normal texts and the max length of them is 2000 though?

**Comment by DRSchlaubi** [comment]
Whoops looks like I didn't notice discord changed that at all.
Uhm okay
But then we should increase the size for Tags.content to something above it because the 2000 limit doesn't account for markdown

My bad sorry

**Review by DRSchlaubi — DISMISSED** [review]
LGTM

**Review by T1Il — APPROVED** [review]

**Comment by T1Il** [comment]
Nice work! 😏

**Pull request merged**
