### PR TITLE
Replace "gebe" with "gib"

### PR DESCRIPTION
**Pull request by base2code**
Please change "Bitte gebe den Inhalt an" with "Bitte gib den Inhalt an". 

This pull request ist just for simplicity, so that this enhancement is not being missed.

Reference: https://www.helpster.de/gib-oder-gebe_196958

### CODE REVIEW

**Comment by base2code** [comment]
If you want you can also change the locally and close with pull request without merging

**Review by daspositioned — APPROVED** [review]

**Comment by daspositioned** [comment]
Thanks for your pull request!

Unfortunately, the build process appears to be failing so we have to wait until it is fixed.

**Comment by DRSchlaubi** [comment]
The build process failing isn't even related to this PR

**Comment by daspositioned** [comment]
I'm aware of that

**Pull request merged**
