### PR TITLE
fix: fast processing for devmarkt requests

### PR DESCRIPTION
**Pull request by T1Il**

### CODE REVIEW

**Comment by NyCodeGHG** [comment]
whats the point of using OkHttp directly, when ktor uses OkHttp as the underlying engine?

**Comment by T1Il** [comment]
The implementation from Schlaubi didn't work as intended, because the parameters wouldn't send properly. After trying to make things work with ktor (it wouldn't), I decided to go the more convenient way with OkHttp. Feel free to change it.

**Comment by DRSchlaubi** [comment]
```kotlin
        bot.httpClient.post<Unit>(config.baseUrl) {
            url {
                path("process.php")
            }

            setBody(formData {
                append("moderator_id", userId.asString)
                append("action", action)
                append("access_token", config.accessToken)
                append("req_id", requestId)
                if (reason != null) {
                    append("reason", reason)
                })
            }
        }
```

This should work (untested)

**Comment by T1Il** [comment]
> ```kotlin
>         bot.httpClient.post<Unit>(config.baseUrl) {
>             url {
>                 path("process.php")
>             }
> 
>             setBody(formData {
>                 append("moderator_id", userId.asString)
>                 append("action", action)
>                 append("access_token", config.accessToken)
>                 append("req_id", requestId)
>                 if (reason != null) {
>                     append("reason", reason)
>                 })
>             }
>         }
> ```
> 
> This should work (untested)

Unfortunately, setBody doesn't exist.

**Comment by NyCodeGHG** [comment]
it's body = ... instead of setBody(...) in ktor 1.6

**Comment by DRSchlaubi** [comment]
Oh I thought you are on 2.0 already haha

**Review by daspositioned — APPROVED** [review]
No idea if this works

**Comment by T1Il** [comment]
> No idea if this works

It works

**Pull request merged**
